services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    environment:
      - 'REDIS_HOSTNAME=redis'
    ports:
      - '6379:6379'

  server:
    restart: always
    build: .
    environment:
      - 'REDIS_HOSTNAME=redis'
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis