spring:
  mvc:
    format:
      date: iso
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        batch_size: 100
        fetch_size: 100
        format_sql: true
        use_sql_comments: true
        use_reflection_optimizer: true
        generate_statistics: true
        cache:
          use_query_cache: true
          use_second_level_cache: true
          factory_class: org.redisson.hibernate.RedissonRegionFactory
          region:
            prefix: ski-resort
          redisson:
            fallback: true
            config: redisson/redisson-dev.yaml
            ski-resort:
              expiration:
                time_to_live: 600000
                max_idle_time: 300000
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret: 
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - openid
              - email
              - profile
  data:
    redis:
      host: ${REDIS_HOSTNAME}
  cache:
    type: redis

google:
  recaptcha:
    key:
      request-method: POST
      request-url: https://www.google.com/recaptcha/api/siteverify
      secret-key:
      site-key:
app:
  image:
    base-path: ./pictures